git #!/bin/bash
git mv 'static/images/4th-of-july/4th Gnome Pillow.png' 'static/images/4th-of-july/4th-gnome-pillow.png'
git mv 'static/images/4th-of-july/4th Ice Cream.png' 'static/images/4th-of-july/4th-ice-cream.png'
git mv 'static/images/4th-of-july/Let_s Celebrate  Gnome.png' 'static/images/4th-of-july/let_s-celebrate-gnome.png'
git mv 'static/images/college/Alabama Crimson Tide Inset.png' 'static/images/college/alabama-crimson-tide-inset.png'
git mv 'static/images/college/Auburn Offset.png' 'static/images/college/auburn-offset.png'
git mv 'static/images/easter/Bunny Unicorn.png' 'static/images/easter/bunny-unicorn.png'
git mv 'static/images/easter/Bunny Girl 1.png' 'static/images/easter/bunny-girl-1.png'
git mv 'static/images/easter/Cute Chick.png' 'static/images/easter/cute-chick.png'
git mv 'static/images/easter/Easter Chick.png' 'static/images/easter/easter-chick.png'
git mv 'static/images/easter/Eggstra Handsome.png' 'static/images/easter/eggstra-handsome.png'
git mv 'static/images/easter/Follw the Bunny.png' 'static/images/easter/follw-the-bunny.png'
git mv 'static/images/easter/Here for the Chicks.png' 'static/images/easter/here-for-the-chicks.png'
git mv 'static/images/easter/Honey Bunny.png' 'static/images/easter/honey-bunny.png'
git mv 'static/images/easter/Little Miss Cotton Tail.png' 'static/images/easter/little-miss-cotton-tail.png'
git mv 'static/images/easter/Lets Hunt Dino.png' 'static/images/easter/lets-hunt-dino.png'
git mv 'static/images/easter/Little Mister Cotton Tail.png' 'static/images/easter/little-mister-cotton-tail.png'
git mv 'static/images/easter/No Bunny Cuter.png' 'static/images/easter/no-bunny-cuter.png'
git mv 'static/images/easter/Peeps Sake.png' 'static/images/easter/peeps-sake.png'
git mv 'static/images/easter/Shake Your Bunny Tail.png' 'static/images/easter/shake-your-bunny-tail.png'
git mv 'static/images/easter/Some Bunny 2.png' 'static/images/easter/some-bunny-2.png'
git mv 'static/images/easter/Some Bunny.png' 'static/images/easter/some-bunny.png'
git mv 'static/images/easter/Love Egg.png' 'static/images/easter/love-egg.png'